#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

mkdir -p $DIR/../OUTPUT/BASE
mkdir -p $DIR/../OUTPUT/ICA
mkdir -p $DIR/../OUTPUT/PCA
mkdir -p $DIR/../OUTPUT/RF
mkdir -p $DIR/../OUTPUT/RP
